name = "CellularAutomata"
uuid = "878138dc-5b27-11ea-1a71-cb95d38d6b29"
authors = ["Francesco Martinuzzi"]
version = "0.0.2"

[deps]


[compat]
julia = "1"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "SafeTestsets", "Random"]
